# Generated by Django 3.2.10 on 2023-02-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NotesTitle', models.CharField(blank=True, max_length=50, null=True)),
                ('NotesDescription', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
