# Generated by Django 3.2.10 on 2023-02-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notedb',
            name='NotesDescription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
